version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  file_handler:
    class: logging.FileHandler
    filename: spark.log
    formatter: simple
  console_handler:
    class: logging.StreamHandler
    formatter: simple
root:
  level: DEBUG
  handlers: [file_handler, console_handler]